version: "3"
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - minio.env
    volumes:
      - ../shared-data/minio:/data
    command: server --console-address ":9001" /data